import subprocess
# Constants
XBt_TO_XBT = 100000000
VERSION = 'v1.1'
try:
    VERSION = str(subprocess.check_output(["git", "describe", "--tags"]).rstrip())
except Exception as e:
    # git not available, ignore
    pass

FLAT = 0
UP = 1
DOWN = 2

ONE_MILLION = 1000000

RULE_1_DOWN_VOLUME = ONE_MILLION
RULE_1_DOWN_VOLUME_RATIO = 3
RULE_1_DOWN_TRADE_GAP = 0.8

RULE_1_UP_VOLUME = 2 * ONE_MILLION
RULE_1_UP_VOLUME_RATIO = 3
RULE_1_UP_TRADE_GAP = 0.8

RULE_2_DOWN_TRADE_GAP = 0.8
RULE_2_UP_TRADE_GAP = 0.8

RULE_3_CONSECUTIVE_UP = 5
RULE_3_CONSECUTIVE_DOWN = 4

RULE_3_HEAD_TAIL_GAP_UP = 1.0
RULE_3_HEAD_TAIL_GAP_DOWN = 1.0

RULE_4_SURGE_VOLUME = 6 * ONE_MILLION
RULE_4_SURGE_TRADE_GAP = 2

RULE_4_PLUNGE_VOLUME = 6 * ONE_MILLION
RULE_4_PLUNGE_TRADE_GAP = 2